name: order

services:
  order-db:
    image: postgres:16-alpine
    container_name: order-db
    ports:
      - "5535:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=orderdb
    volumes:
      - /Volumes/Backup/DockerSSD/whitelabel/orderdb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d orderdb"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s
    networks:
      - whitelabel-network

  order-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-app
    ports:
      - "8084:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/orderdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
    depends_on:
      order-db:
        condition: service_healthy
    networks:
      - whitelabel-network

networks:
  whitelabel-network:
    external: true
