package com.whitelabel.order.controller;

import com.whitelabel.order.dto.OrderRequestDTO;
import com.whitelabel.order.dto.OrderResponseDTO;
import com.whitelabel.order.dto.PageResponseDTO;
import com.whitelabel.order.service.IOrderService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springdoc.core.annotations.ParameterObject;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;
import java.util.UUID;

@Tag(
        name = "Orders",
        description = "Customer orders. An order is created with its items in a single request, and the "
                + "`orderNumber` is generated by the server — never sent by the client."
)
@RestController
@RequestMapping("/api/v1/orders")
@RequiredArgsConstructor
class OrderController {
    private final IOrderService orderService;

    private static final String ORDER_EXAMPLE = """
            {
              "orderItemList": [
                {
                  "sku": "REDMI-18-BLACK-128",
                  "price": 3000.00,
                  "quantity": 1
                },
                {
                  "sku": "CAPA-SILICONE-PRETA",
                  "price": 50.00,
                  "quantity": 2
                }
              ]
            }
            """;


    @Operation(
            summary = "Create an order",
            description = "Creates the order and all of its items in one shot — the items cascade from the "
                    + "order, so there is no separate endpoint to add an item. The request must carry at "
                    + "least one item."
    )
    @ApiResponse(responseCode = "201", description = "Order created")
    @ApiResponse(responseCode = "400", description = "Validation error (empty item list, blank sku, price or quantity out of range)")
    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    public OrderResponseDTO create(
            @Valid @io.swagger.v3.oas.annotations.parameters.RequestBody(
                    description = "The items that make up the order", required = true,
                    content = @Content(schema = @Schema(implementation = OrderRequestDTO.class),
                            examples = @ExampleObject(name = "Order with two items", value = ORDER_EXAMPLE)))
            @RequestBody OrderRequestDTO orderRequestDTO, @AuthenticationPrincipal Jwt jwt) {
        return orderService.create(orderRequestDTO, jwt.getSubject());
    }

    @Operation(
            summary = "List orders (paginated)",
            description = "Pages are 10 items by default: `?page=0&size=10&sort=createdAt,desc`. "
                    + "Each order comes with its full item list under `orderItemList`."
    )
    @ApiResponse(responseCode = "200", description = "Page of orders")
    @GetMapping
    @ResponseStatus(HttpStatus.OK)
    public PageResponseDTO<OrderResponseDTO> findAll(@ParameterObject Pageable pageable, @AuthenticationPrincipal Jwt jwt) {
        String userId = jwt.getSubject();

        boolean isAdmin = false;

        Map<String, Object> realAccess = jwt.getClaim("realm_access");

        if (realAccess != null && realAccess.containsKey("roles")) {
            List<String> roles = (List<String>) realAccess.get("roles");

            isAdmin = roles.stream().anyMatch(role -> role.equalsIgnoreCase("ADMIN"));
        }

        return orderService.findAll(pageable, userId, isAdmin);
    }

    @Operation(
            summary = "Get an order by id",
            description = "Returns the order with every item that belongs to it."
    )
    @ApiResponse(responseCode = "200", description = "Order found")
    @ApiResponse(responseCode = "404", description = "Order not found")
    @GetMapping("/{id}")
    @ResponseStatus(HttpStatus.OK)
    public OrderResponseDTO findById(@PathVariable UUID id) {
        return orderService.findById(id);
    }

    @Operation(
            summary = "Delete an order",
            description = "Deletes the order and cascades to every item inside it."
    )
    @ApiResponse(responseCode = "204", description = "Deleted")
    @ApiResponse(responseCode = "404", description = "Order not found")
    @DeleteMapping("/{id}")
    @ResponseStatus(HttpStatus.NO_CONTENT)
    public void delete(@PathVariable UUID id) {
        orderService.delete(id);
    }
}
