name: category

services:
  category-db:
    image: postgres:16-alpine
    container_name: category-db
    ports:
      - "5533:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=categorydb
    volumes:
      - /Volumes/Backup/DockerSSD/whitelabel/categorydb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d categorydb"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s
    networks:
      - whitelabel-network

  category-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: category-app
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://category-db:5432/categorydb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
    depends_on:
      category-db:
        condition: service_healthy
    networks:
      - whitelabel-network

networks:
  whitelabel-network:
    external: true
