name: stock

services:
  stock-db:
    image: postgres:16-alpine
    container_name: stock-db
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /Volumes/Backup/DockerSSD/whitelabel/stockdb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s
    networks:
      - whitelabel-network

  stock-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-app
    env_file:
      - .env
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
    depends_on:
      stock-db:
        condition: service_healthy
    networks:
      - whitelabel-network

networks:
  whitelabel-network:
    external: true
